const IMAGES = {
  gallery: [
    new URL("./gallery/4b421_md.png", import.meta.url).href,
    new URL("./gallery/005-DriverlessCar_md.png", import.meta.url).href,
    new URL("./gallery/abundance_md.png", import.meta.url).href,
    new URL("./gallery/ALLIN_fondosmall_md.png", import.meta.url).href,
    new URL("./gallery/AWTY_Dribbble_md.png", import.meta.url).href,
    new URL("./gallery/billboard_md.png", import.meta.url).href,
    new URL("./gallery/brand_grill_md.png", import.meta.url).href,
    new URL("./gallery/chinatown_md.png", import.meta.url).href,
    new URL("./gallery/Circusbear_md.png", import.meta.url).href,
    new URL("./gallery/cny_edit_md.png", import.meta.url).href,
    new URL("./gallery/collage_toast_md.png", import.meta.url).href,
    new URL("./gallery/cuyes_nuevo_amanecerB_md.png", import.meta.url).href,
    new URL("./gallery/Egypt_palette_md.png", import.meta.url).href,
    new URL("./gallery/fondo_md.png", import.meta.url).href,
    new URL("./gallery/green_md.png", import.meta.url).href,
    new URL("./gallery/H_Dribbble_md.png", import.meta.url).href,
    new URL("./gallery/Havi_new_md.png", import.meta.url).href,
    new URL("./gallery/insurance_md.png", import.meta.url).href,
    new URL("./gallery/Invisible_md.png", import.meta.url).href,
    new URL("./gallery/kat_md.png", import.meta.url).href,
    new URL("./gallery/Logo-Measures-Final_md.gif", import.meta.url).href,
    new URL("./gallery/Logos_simple_md.png", import.meta.url).href,
    new URL("./gallery/MA_I436653full_md.png", import.meta.url).href,
    new URL("./gallery/madefordigital2_md.png", import.meta.url).href,
    new URL("./gallery/mixed_001_md.gif", import.meta.url).href,
    new URL("./gallery/mixed_002_md.gif", import.meta.url).href,
    new URL("./gallery/mixed_003_md.png", import.meta.url).href,
    new URL("./gallery/mixed_005_md.png", import.meta.url).href,
    new URL("./gallery/mixed_006_md.png", import.meta.url).href,
    new URL("./gallery/mixed_008_md.png", import.meta.url).href,
    new URL("./gallery/mixed_009_md.png", import.meta.url).href,
    new URL("./gallery/Moow_md.png", import.meta.url).href,
    new URL("./gallery/orange_md.png", import.meta.url).href,
    new URL("./gallery/Round_md.gif", import.meta.url).href,
    new URL("./gallery/PearGrain_md.png", import.meta.url).href,
    new URL("./gallery/Ski_mountain_md.png", import.meta.url).href,
    new URL("./gallery/Social_keyvisual_md.png", import.meta.url).href,
    new URL("./gallery/UI_countdown_md.png", import.meta.url).href,
  ],
  other: {
    footergallerybg730: new URL(
      "./other/footer-gallerybg-730.png",
      import.meta.url
    ).href,
    branding1: new URL("./other/branding_1.png", import.meta.url).href,
    branding2: new URL("./other/branding_2.png", import.meta.url).href,
    branding3: new URL("./other/branding_3.png", import.meta.url).href,
    branding4: new URL("./other/branding_4.png", import.meta.url).href,
    project1: new URL("./other/project1.png", import.meta.url).href,
  },
  socials: {
    email: new URL("./socials/email.svg", import.meta.url).href,
    behance: new URL("./socials/behance.svg", import.meta.url).href,
    github: new URL("./socials/github.svg", import.meta.url).href,
    instagram: new URL("./socials/instagram.svg", import.meta.url).href,
    dribbble: new URL("./socials/dribbble.svg", import.meta.url).href,
    linkedin: new URL("./socials/linkedin.svg", import.meta.url).href,
  },
};

export default IMAGES;
